#!/bin/bash

set +ex

# expected arguments are
# folder environment function name => then the rest

SOURCE_FOLDER=$1

cd $SOURCE_FOLDER
npm install
npm prune

# yank out the node modules and empty folder
cd ../
mv ../node_modules .
rm -rf $SOURCE_FOLDER
mkdir $SOURCE_FOLDER
mv node_modules $SOURCE_FOLDER
