steps:

- name: 'gcr.io/kaniko-project/executor:latest'
  id: BuildImage
  args:
    - --destination=gcr.io/$PROJECT_ID/node-ci
    - --cache=true

- name: 'gcr.io/$PROJECT_ID/node-ci'
  id: ListNode
  args: ['node', '--version']
  waitFor:
  - BuildImage

- name: 'gcr.io/$PROJECT_ID/node-ci'
  id: ListGcloud
  args: ['gcloud', 'components', 'list']
  waitFor:
  - BuildImage

images: ['gcr.io/$PROJECT_ID/node-ci']
