#!/bin/bash

set +ex

# expected arguments are
# folder environment function name => then the rest

SOURCE_FOLDER=$1
NODE_ENV=$2
FUNCTION_NAME=$3

# transpile
cd $SOURCE_FOLDER
echo "transpiling $SOURCE_FOLDER for $NODE_ENV environment"
yarn install
echo 'end npm install'

# total misfire here, we don't need to prune the packaker, we upload the json file and cloud functions does that.
# make sure there are no dupes slash we have to do this for some packages
# in npm 5.[2|3|4] this fucks everything up
# had to downgrade to npm@4 to get out of it
# npm prune

yarn run "package-functions-${NODE_ENV}"

# TODO: create the source contexts
# this doesn't work right now because we'd need to
#   1. commit the transpiled code
#   2. create these source files
#   3. push that back to GitHub and do a deploy
# gcloud debug source gen-repo-info-file --output-directory functions

# deploy
DEPLOY_COMMAND="gcloud beta functions deploy ${FUNCTION_NAME}-${NODE_ENV} ${@:4}"
echo "deploying $DEPLOY_COMMAND"
cd functions && $DEPLOY_COMMAND
