#!/bin/bash

set +ex

# expected argument is environment, with FIREBASE_TOKEN set in the env
# maybe more in the future for all the function-specific ones like timeout and memory.

SOURCE_FOLDER=$1
ENVIRONMENT=$2

# to switch to where the script is being called from
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

cd $SOURCE_FOLDER
npm install
npm run "deploy-${ENVIRONMENT}" --token "${FIREBASE_TOKEN}"
