#!/bin/bash

set +ex

# expected argument is environment, with FIREBASE_TOKEN set in the env
# maybe more in the future for all the function-specific ones like timeout and memory.

cd $SOURCE_FOLDER
npm install
npm run "deploy-${ENVIRONMENT}" --token "${FIREBASE_TOKEN}"
